---
#- name: make directory
#  file:
#    state: directory
#    path: "{{ item.path }}"
#    owner: root
#    group: root
#    mode: "0755"
#  with_items:
#    - path: /etc/nginx/conf.alias
#    - path: /etc/nginx/init.d

- name: set config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - src: etc/nginx/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: "0644"
  notify: restart nginx
