---
auto_scaling_group:
  official:
    name: asg-{{ global.project_id }}-{{ global.env_id}}-official
    load_balancers: elb-wt-prd-official
    availability_zones:
      - ap-northeast-1a
    launch_config_name: lc-wt-prd-official
    min_size: 1
    max_size: 1
    desired_capacity: 1
    vpc_zone_identifier:
      - subnet-317c9978