---
elb_etc:
  role: "webap"
elb:
  webap:
    name: elb-{{ global.project_id }}-{{ global.env_id }}-{{ elb_etc.role }}
    env: "{{ global.env_id }}"
    role: "{{ elb_etc.role }}"
    subnets:
      - subnet-6372972a
      - subnet-d3fea68b
    listeners:
      - protocol: https
        load_balancer_port: 443
        instance_protocol: http
        instance_port: 80
        ssl_certificate_id: "arn:aws:acm:ap-northeast-1:961290755580:certificate/b788e720-009e-466f-87d1-8364441d1dda"
    security_group_names:
      - wt-prd-sg-https-gc-stitch
      - wt-prd-sg-https-gc-lilo
      - wt-prd-sg-https-northern
    cross_az_load_balancing: yes
    health_check:
        ping_protocol: http
        ping_port: 80
        ping_path: "/"
        response_timeout: 20
        interval: 30
        unhealthy_threshold: 3
        healthy_threshold: 2
    access_logs:
        interval: 5
        s3_location: project-prd-accesslogs
        s3_prefix: wt-prd-webap
