- name: launch instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: instance
      vars_file: forami-wt-dev-deploy.yml

- name: Configure instance(s)
  hosts: launched
  become: yes
  gather_facts: no
  roles:
    - ../common_playbooks/roles/timezone
    - ../common_playbooks/roles/cloud-config
    - ../common_playbooks/roles/amazon-linux-ami-repository-2017.03
    - ../common_playbooks/roles/perman_groups
    - ../common_playbooks/roles/openssh-ldap-6.6.1p1-33.66.amzn1.x86_64
    - ../common_playbooks/roles/nss-pam-ldapd-0.7.5-20.12.amzn1.x86_64
    - ../common_playbooks/roles/authconfig-6.2.8-30.31.amzn1.x86_64
    - ../common_playbooks/roles/jdk-8u141-linux-x64
    - ../common_playbooks/roles/jenkins-2.74-1.1.noarch
    - ../common_playbooks/roles/awscli-1.11.127
    - ../common_playbooks/roles/mysql56.x86_64
    - role: bash_profile
      vars_file: forami-wt-dev-deploy.yml
