- name: launch instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: instance
      vars_file: forami-wt-dev-jetprofiler.yml

- name: Configure instance(s)
  hosts: launched
  become: yes
  gather_facts: no
  roles:
    - ../common_playbooks/roles/timezone
    - ../common_playbooks/roles/cloud-config
    - ../common_playbooks/roles/server-with-gui
    - ../common_playbooks/roles/tigervnc-server-1.8.0-1.el7.x86_64
    - ../common_playbooks/roles/jdk-8u141-linux-x64
    - ../common_playbooks/roles/jetprofiler-3.0.10