- name: launch instance
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: launch_configuration
      vars_file: webap.yml
    - role: target_group
      vars_file: webap.yml
    - role: alb
      vars_file: webap.yml
    - role: auto_scaling_group
      vars_file: webap.yml

