---
auto_scaling_group:
  webap:
    name: asg-{{ global.project_id }}-{{ global.env_id}}-webap
    region: "{{ global.region }}"
    availability_zones:
      - ap-northeast-1a
    min_size: 1 
    max_size: 2
    desired_capacity: 1
    vpc_zone_identifier:
      - subnet-e2799cab
