---
- name: Ensures /home/ec2-user/db_init/db-schema dir exists
  file: 
    path: /home/ec2-user/db_init/db-schema 
    state: directory

- name: Copy SQL Script to /home/ec2-user/db_init/db-schema
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ db_init.db_schema_batch }}"

- name: Get RDS Instance
  rds:
    region: "{{ db_init.instances.region }}"
    command: facts
    instance_name: "{{ db_init.instances.name }}"
  register: _rds_instance

- name: Create project DB Schemas
  mysql_db: 
    login_host: "{{ _rds_instance.instance.endpoint }}"
    login_password: "{{ db_init.db_auth.login_password }}"
    login_user: "{{ db_init.db_auth.login_user }}"
    login_port: "{{ db_init.db_auth.login_port }}"
    name: all
    state: import
    target: "/home/ec2-user/db_init/db-schema/init.sql"
