---
- name: install jenkins plugins
  jenkins_plugin:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: "{{ item.state }}"
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins

- name: set script approval
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ script_approval }}"
  notify: restart jenkins
