---
- name: execute authconfig
  command: authconfig {{ item.command }}
  with_items: "{{ auth_command }}"

- name: update ldap_config, sudoers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ ldap_files }}"
  notify: restart nslcd
