---
- name: create security_group use source groups
  ec2_group:
    name: "{{ item.value.group_name }}"
    description: "{{ item.value.description }}"
    vpc_id: "{{ vpc_net_fact.vpcs[0].id }}"
    region: "{{ security_group_etc.region }}"
    rules: >-
      {%- if item.value.rules|length == 1 -%}
        {{ item.value.rules }}
      {%- else -%}
        {{ item.value.rules | join(',') }}
      {%- endif -%}
  with_dict: "{{ security_group_use_source_groups }}"
